### ISSUE TITLE
Increase max number of Logs in file

### ISSUE THREAD

**Issue by alexeystn** [cleanflight/blackbox-tools#21]
I use 'blackbox_decode' for retrieving GPS tracks from iNav logs.
Sometimes it happens that a single file contains more than 31 logs.
For this reason I increased constant FLIGHT_LOG_MAX_LOGS_IN_FILE.
Is there any reason why is it limited now? Could it be increased in next release?

https://github.com/cleanflight/blackbox-tools/blob/3c0b9ea8c52c4fdecd67f8d622e2a778bbe1279d/src/parser.h#L10

Thank you!

**Comment by bw1129** [comment]
I have the same problem when using blackbox_decode with PIDtoolbox when log files have more than 31 files. The problem arises typically on FCs with flash drives because Betaflight generates a small file every time the FC is initiated, that appears as a "paused file" in Blackbox explorer, and makes it impossible to access the data files > #31. Is there a reason for this limitation, or better is there a simple way to override it?
